const bookingData = [
    {
        id: 1,
        customerName: 'John Doe',
        workspaceName: 'Downtown Office',
        startTime: '09:00 AM',
        endTime: '05:00 PM',
        bookingDate: '2024-07-01',
        amount: 100,
        paymentState: 'Paid',
        conferenceRoom: 'Room A',
        numberOfPersons: 5,
    },
    {
        id: 2,
        customerName: 'Jane Smith',
        workspaceName: 'Midtown Office',
        startTime: '10:00 AM',
        endTime: '06:00 PM',
        bookingDate: '2024-07-02',
        amount: 120,
        paymentState: 'Unpaid',
        conferenceRoom: 'Room B',
        numberOfPersons: 10,
    },
    {
        id: 3,
        customerName: 'Alice Johnson',
        workspaceName: 'Uptown Office',
        startTime: '08:00 AM',
        endTime: '04:00 PM',
        bookingDate: '2024-07-03',
        amount: 90,
        paymentState: 'Pending',
        conferenceRoom: 'Room C',
        numberOfPersons: 3,
    },
    {
        id: 4,
        customerName: 'Bob Brown',
        workspaceName: 'Suburban Office',
        startTime: '11:00 AM',
        endTime: '07:00 PM',
        bookingDate: '2024-07-04',
        amount: 150,
        paymentState: 'Paid',
        conferenceRoom: 'Room D',
        numberOfPersons: 8,
    },
    {
        id: 5,
        customerName: 'Carol Green',
        workspaceName: 'Riverside Office',
        startTime: '07:00 AM',
        endTime: '03:00 PM',
        bookingDate: '2024-07-05',
        amount: 110,
        paymentState: 'Unpaid',
        conferenceRoom: 'Room E',
        numberOfPersons: 6,
    },
];

export default bookingData;
